#TRK-4F41B1FD
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agentregistry-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "agentregistry.labels.app" . }}
    component: agentregistry
    name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "agentregistry.labels.app" . }}
    component: agentregistry
    name: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP

