{{- if .Values.app.useBringYourOwnCert }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-custom-tls-secret-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-cert-gen-sa
      restartPolicy: OnFailure
      containers:
      - name: create-tls-secret
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          echo "Creating TLS secret from provided certificate and key..."
          
          # Check if secret already exists
          if kubectl get secret {{ .Release.Name }}-tls-secret -n {{ .Release.Namespace }} 2>/dev/null; then
            echo "Secret already exists, deleting old one..."
            kubectl delete secret {{ .Release.Name }}-tls-secret -n {{ .Release.Namespace }}
          fi
          
          # Create secret from provided certificate and key
          kubectl create secret tls {{ .Release.Name }}-tls-secret \
            --cert=/tmp/tls.crt \
            --key=/tmp/tls.key \
            -n {{ .Release.Namespace }}
          
          echo "TLS secret created successfully!"
        volumeMounts:
        - name: tls-cert
          mountPath: /tmp/tls.crt
          subPath: tls.crt
        - name: tls-key
          mountPath: /tmp/tls.key
          subPath: tls.key
      volumes:
      - name: tls-cert
        secret:
          secretName: {{ .Release.Name }}-tls-cert-temp
      - name: tls-key
        secret:
          secretName: {{ .Release.Name }}-tls-key-temp
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-cert-temp
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
type: Opaque
stringData:
  tls.crt: {{ .Values.app.bringYourOwntlsCert | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-key-temp
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
type: Opaque
stringData:
  tls.key: {{ .Values.app.bringYourOwntlsKey | quote }}
{{- end }}
