apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cert-gen-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-cert-gen-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "patch", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-cert-gen-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cert-gen-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-cert-gen-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-nginx-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-nginx-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-nginx-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.labels.app" . }}
    component: nginx
    name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-nginx-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-nginx-role
  apiGroup: rbac.authorization.k8s.io